# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user91\Documents\ydong\python\tool\WeChat_Dat_To_Image\WDTI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(353, 326)
        Form.setMinimumSize(QtCore.QSize(353, 326))
        Form.setMaximumSize(QtCore.QSize(353, 326))
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(264, 30, 81, 23))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 90, 331, 231))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 241, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 60, 241, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.datToPic) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dat Converter"))
        self.pushButton.setText(_translate("Form", "Action"))
        self.textBrowser.setPlaceholderText(_translate("Form", "progress information"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Please input dat file path"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Please input tar  file path"))
